language: ruby
cache: bundler
before_script:
 - chmod +x ./script/cibuild # or do this locally and commit
script:
 - ./scripts/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
